SiliconWebApplication/Controllers/SecurityController.cs
using SiliconWebApplication.ViewModels.Account;
using Infrastructure.Contexts;
using Infrastructure.Entities;
using Infrastructure.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace SiliconWebApp.Controllers;

public class SecurityController : Controller
{

    private readonly UserManager<UserEntity> _userManager;
    private readonly AddressServices _addressServices;
    private readonly SignInManager<UserEntity> _signInManager;

    public SecurityController(UserManager<UserEntity> userManager, AddressServices addressServices, SignInManager<UserEntity> signInManager)
    {
        _userManager = userManager;
        _addressServices = addressServices;
        _signInManager = signInManager;
    }

    [HttpGet]
    [Route("/Security")]
    public async Task<IActionResult> Security()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return RedirectToAction("Login", "Account");
        }

        var viewModel = new AccountDetailsViewModel
        {
            ProfileInfo = new ProfileInfoViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email!
            }
        };

        return View(viewModel);
    }


    [HttpPost]
    [Route("/Security")]
    public async Task<IActionResult> Security(AccountSecurityViewModel model)
    {
        if (!ModelState.IsValid)
        {
          
            return View(model);
        }

     
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return RedirectToAction("Login", "Auth");
        }

        var changePasswordResult = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
        if (!changePasswordResult.Succeeded)
        {
            foreach (var error in changePasswordResult.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }


        return RedirectToAction("SecurityConfirmation");
    }

    [HttpGet]
    [Route("/SecurityConfirmation")] 
    public IActionResult SecurityConfirmation()
    {
        return View(); 
    }


    [HttpPost]
    [Route("/account/delete")]
    public async Task<IActionResult> Delete()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return RedirectToAction("Login", "Account");
        }

        // Ta bort användarens adress om den finns
        var address = await _addressServices.GetAddressAsync(user.Id);
        if (address != null)
        {
            await _addressServices.DeleteAddressAsync(user.Id);
        }

        // Ta bort användaren
        var result = await _userManager.DeleteAsync(user);
        if (!result.Succeeded)
        {
            // Misslyckades med att ta bort användaren, hantera felet här
            return RedirectToAction("DeleteFailure");
        }

        ;
        return RedirectToAction("DeleteConfirmation");
    }




    [HttpGet]
    [Route("/Deletefirmation")]
    public async Task<ActionResult> DeleteConfirmation()
    {
        await _signInManager.SignOutAsync();
        return View();
    }


    [HttpGet]
    [Route("/DeleteFailure")]
    public IActionResult DeleteFailure()
    {
        return View();
    }



}

SiliconWebApplication/Views/Security/DeleteConfirmation.cshtml
<div class="container">
    <h4>
        Your account has been successfully deleted.
    </h4>
    <div>
        <a asp-controller="Home" asp-action="Home" class="btn-theme"><i class="fa-regular fa-user"></i><span>Go Home</span></a>
    </div>

</div>

SiliconWebApplication/Views/Security/DeleteFailure.cshtml
<div class="container">
    <h4>
        Something went wrong, your account has not been deleted.
    </h4>
    <div>
        <a asp-controller="Security" asp-action="Security" class="btn-theme"><i class="fa-regular fa-user"></i><span>Go Back</span></a>
    </div>

</div>

SiliconWebApplication/Views/Security/Security.cshtml
@* @model SiliconWebApplication.ViewModels.Account.AccountSecurityViewModel *@
@model AccountDetailsViewModel
@{
    ViewData["Title"] = "Security";
}
<link rel="stylesheet" href="~/css/Security.css" asp-append-version="true" />
@* <link rel="stylesheet" href="~/css/AccountDetails.css" asp-append-version="true" />  *@
<section class="details">
    <div class="container container-profil">

        <partial name="~/Views/Shared/AsideAccount/AsideAccount.cshtml" />
      
        <div class="infoDetails">
            <div class="createNewSecurity">
                <h1>Security</h1>
                <h5 class="colorTitle">Change Password</h5>
                <form method="post">
                    <div class="clientInfo">
                        <div class="oldPassword">
                            <label asp-for="Accountsecurity.OldPassword"><b>Current Password</b></label>
                            <input asp-for="Accountsecurity.OldPassword" type="password" placeholder="Enter current password" name="OldPassword">
                            <span asp-validation-for="Accountsecurity.OldPassword" class="text-danger"></span>
                        </div>
                    </div>                 

                    <div class="clientInfo">
                        <div class="clienSecurity">
                            <label asp-for="Accountsecurity.NewPassword"><b>New Password</b></label>
                            <input asp-for="Accountsecurity.NewPassword" type="password" placeholder="Enter new password" name="NewPassword">
                            <span asp-validation-for="Accountsecurity.NewPassword" class="text-danger"></span>
                        </div>
                        <div class="clienSecurity">
                            <label asp-for="Accountsecurity.ConfirmNewPassword"><b>Confirm New Password</b></label>
                            <input asp-for="Accountsecurity.ConfirmNewPassword" type="password" placeholder="Confirm new password" name="ConfirmNewPassword">
                            <span asp-validation-for="Accountsecurity.ConfirmNewPassword" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="acountbutton">
                        <button class="btn-gray" type="reset">Cancel</button>
                        <button class="btn-theme" type="submit">Save Changes</button>
                    </div>
                </form>
            </div>

            <hr>
            <form asp-action="Delete" asp-controller="Security" method="post">
                <div class="address">
                    <h5 class="colorTitle">Delete account</h5>
                    <p class="text-m">When you delete your account, your public profile will be deactivated immediately. If you change your mind before the 14 days are up, sign in with your email and password, and we’ll send you a link to reactivate your account.</p>

                    <div class="securityCheck">
                        <input type="checkbox" id="agreeCheckbox" name="agreeCheckbox">
                        <label for="agreeCheckbox">I agree to the <a href="#">Terms</a> & <a href="#">Conditions</a></label>
                        <button type="submit" class="btn-delete">Delete</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
   
</section>

SiliconWebApplication/Views/Security/SecurityConfirmation.cshtml
<div class="container">
    <h4>
        Your password is successfully Changed.
    </h4>
    <div>
        <a asp-controller="Security" asp-action="Security" class="btn-theme"><i class="fa-regular fa-user"></i><span>Go Back </span></a>
    </div>

</div>